macro (setup_config)
    if (UNIX)
        add_compile_definitions(_M_UNIX)
        set(BM_APP_WINDOWED "")
        set(BM_UNIX "TRUE")
    elseif(WIN32)
        add_compile_definitions(_M_WIN32)
        set(BM_APP_WINDOWED WIN32)
        set(BM_WIN32 "TRUE")
    endif ()

    #------------------------------------------------------------------------------
    #Implementation
    #------------------------------------------------------------------------------
    #renderer defines
    if(BM_DEFAULT_RENDERER STREQUAL "BM_DX12")
        if(BM_UNIX)
            message(FATAL_ERROR "There is no support for DX12 on unix platforms, can't be default renderer")
        endif()
        set(BM_DX12_DEFAULT_RENDERER "TRUE")
        add_compile_definitions(_M_DX12_DEFAULT_RENDERER)
    elseif(BM_DEFAULT_RENDERER STREQUAL "BM_VULKAN")
        set(BM_VULKAN_DEFAULT_RENDERER "TRUE")
        add_compile_definitions(_M_VULKAN_DEFAULT_RENDERER)
    endif()

    if(BM_ALL_RENDERER)
        add_compile_definitions(_M_ALL_RENDERER)
        if(BM_UNIX)
            message(WARNING "There is no support for DX12 on unix platforms")
        else()
            list(APPEND BM_RENDERERS DX12Renderer)
            add_compile_definitions(_M_DX12_RENDERER)
            set(BM_DX12_RENDERER "TRUE")
        endif()
        list(APPEND BM_RENDERERS VulkanRenderer)
        add_compile_definitions(_M_VULKAN_RENDERER)
        set(BM_VULKAN_RENDERER "TRUE")
    else()
        if(BM_DX12_DEFAULT_RENDERER)
            if(BM_UNIX)
                message(FATAL_ERROR "There is no support for DX12 on unix platforms")
            endif()
            list(APPEND BM_RENDERERS DX12Renderer)
            add_compile_definitions(_M_DX12_RENDERER)
        elseif(BM_VULKAN_DEFAULT_RENDERER)
            list(APPEND BM_RENDERERS VulkanRenderer)
            add_compile_definitions(_M_VULKAN_RENDERER)
        endif()
    endif()

    #Build defines
    if(BM_DYNAMIC_LINK)
        add_compile_definitions(_M_DLL_DYNAMIC_LINK)
    endif()
endmacro()